import Head from 'next/head'
import { Editor } from '../src/components/Editor'

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<Editor />
			</main>
		</div>
	)
}
